# 1. Configuraci\u00f3n B\u00e1sica
spring.application.name=api-gateway
server.port=8080
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# 2. apagar creaci\u00f3n autom\u00e1tica de rutas en Spring Cloud Gateway
spring.cloud.gateway.discovery.locator.enabled=false

#crear la regla del inventario
spring.cloud.gateway.routes[0].id=ruta-inventario
spring.cloud.gateway.routes[0].uri=http://localhost:8082
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/inventario/**

# 4. Creamos la regla de Ventas
spring.cloud.gateway.routes[1].id=ruta-ventas
spring.cloud.gateway.routes[1].uri=lb://MS-VENTAS
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/ventas/**