# 1. Nombre y puerto principal
spring.application.name=eureka-server
server.port=8761

# el principal no se busca ni se registra asi mismo, reglas principales.
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false